services:
  authservice:
    build: ./node/authService
    ports:
      - "5001:5001"
    networks:
      - app-network

  userservice:
    build: ./node/userservice
    ports:
      - "5002:5002"
    depends_on:
      - authservice
    networks:
      - app-network

  productservice:
    build: ./java/productService
    ports:
      - "5004:5004"
    depends_on:
      - authservice
    networks:
      - app-network

  paymentservice:
    build: ./java/paymentService
    ports:
      - "5005:5005"
    depends_on:
      - authservice
    networks:
      - app-network

networks:
  app-network:
