services:
  authservice:
    build: ./node/authService
    ports:
      - "5001:5001"
    networks:
      - app-network

  userservice:
    build: ./node/userservice
    ports:
      - "5002:5002"
    depends_on:
      - authservice
    networks:
      - app-network

networks:
  app-network:
